number1= input('Enter number1:')
number2= input('Enter number 2:')
number3= input('Enter number3:')
number4= input('Enter number4:')
number5= input('Enter number5:')
sum= int (number3)+int(number5)+int(number4)+int(number2)
print(sum)
